# Generated by Django 5.2.14 on 2026-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
                ('topic', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
