# Generated by Django 5.2.14 on 2026-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_studylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
