# Generated by Django 5.2.14 on 2026-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_profile_bio_alter_profile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('mentor', 'Mentor')], default='student', max_length=20),
        ),
    ]
