# Generated by Django 5.2.14 on 2026-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_profile_level_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
