# Generated by Django 5.2.14 on 2026-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
