# Generated by Django 5.2.14 on 2026-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_profile_best_streak_profile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_goal',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_goal',
            field=models.FloatField(default=10),
        ),
    ]
